spring:
  application:
    name: eureka-service-alpha
server:
  port: 8000

eureka:
  ##修改UI上的环境信息为Alpha
  environment: Alpha
  ##修改UI上的数据中心名称为AlphaCenter
  datacenter: AlphaCenter
  client:
    service-url:
      ##默认区域控制UI地址 注册到9000端口的Eureka服务中心上
      defaultZone: http://eureka-service2:9000/eureka/
  instance:
    hostname: eureka-service1









