spring:
  application:
    name: eureka-service-beta
server:
  port: 9000
eureka:
  ##修改UI上的环境信息为Beta
  environment: Beta
  ##修改UI上的数据中心名称为BetaCenter
  datacenter: BetaCenter
  client:
    service-url:
      ##默认区域控制UI地址
      defaultZone: http://${eureka.instance.hostname}:8000/eureka
  instance:
    hostname: eureka-service2








